---
title: "Statistiques descriptives"
---

## **Vous trouverez ici une page complète de statistiques descriptive pour les données d'énergie et de d'espérance de vie.**

# Statistiques descriptives

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(countrycode)
library(gsheet)
library(psych)
library(lubridate)
library(doBy)
library(purrr)
library(leaflet)
library(sf)
library(leafdown)
library(rgdal)
library(highcharter)
library(ggthemes)

currentDate <- Sys.Date()
csvFileName2finale <- paste("data/processed/cbin_dat.csv",sep = "")
tab1 <- read.csv("data\\tab1.csv")
tab2 <- read.csv("data\\tab2.csv")
tab3 <- read.csv("data\\tab3.csv")
dat2 <- read.csv(csvFileName2finale)

getwd()
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# Consommation d'énergie par capita, regroupé par continent au 21e siècle.

tab1

# Statistiques descriptive sur la durée de vie par quinquagénaire

tab2

# Statistiques intertemporelles sur la production des énergies les plus importante

tab3 

# Statistiques descriptives par continant

df1 <- data.frame(grpBy=dat2$continent, dat2$gdp, dat2$electricity_demand, dat2$electricity_generation, dat2$gas_prod_change_pct, dat2$Life.expectancy) %>% split(.$grpBy) %>% map(summary)

df1

```
